if_red: False
is_record: False
ifshow: True
fps_mode: 0
exp_time: 30000

sensor_far:
  deviceID: 0
  rcd_path:  "/home/bismarck/radar/far"
  window_name: 'far'
  rows: 1200
  cols: 1600
  fps: 400
  cx: 856.0181
  cy: 677.7472
  fx: 1770.0599
  fy: 1780.9150
  distcoef1: -0.0543
  distcoef2: -0.76375
  distcoef3: -0.005395
  distcoef4: 0.00523
  distcoef5: 5.0340


sensor_close:
  deviceID: 1
  rcd_path: "/home/bismarck/radar/close"
  window_name: 'close'

AlgParams:
  H_min: 111
  H_max: 162
  S_min: 192
  S_max: 255
  V_min: 134
  V_max: 255

  H_minr: 0
  H_maxr: 10
  S_minr: 43
  S_maxr: 255
  V_minr: 46
  V_maxr: 255


#llj:change paramaters in this file, don't need to cmake again
#bglbannery
